Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -32,7 +32,7 @@ jobs:
         working-directory: apps/pusula
         run: |
           export PATH=$PATH:~/.local/bin
-          yes | buildozer -v android debug
+          buildozer -v android debug || (echo "BUILD FAILED"; exit 1)
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
